### ISSUE TITLE
HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by sdecaux** [baracudaz/netatmo-lametric-proxy#7]
Version of Feb 9, 2016 is working fine
`Detected other  : 03:00:00:01:59:96 'Garage' - NAModule4, Temperature, CO2, Humidity
Detected other  : 05:00:00:00:2d:00 'Pluvio' - NAModule3, Rain
Detected station: 70:ee:50:00:50:bc 'Intérieur' - NAMain, Temperature, CO2, Humidity, Noise, Pressure
Detected module : 02:00:00:00:3e:3e 'Exterieur' - NAModule1, Temperature, Humidity
{'trend': 'stable', 'pressure': '1017.7mb', 'temperature': '14.7\xc2\xb0C', 'humidity': '100%'}
`

But When I try the new version, transferring exactly the same USER SPECIFIC INFORMATION to config.ini, I now have an error:
`Traceback (most recent call last):
  File "./updateLaMetric.py", line 48, in <module>
    authorization = lnetatmo.ClientAuth(client_id, client_secret, username, password)
  File "/Volumes/Beta/Web/netatmo-lametric-proxy-master/v3/library/lnetatmo.py", line 61, in __init__
    resp = postRequest(_AUTH_REQ, postParams)
  File "/Volumes/Beta/Web/netatmo-lametric-proxy-master/v3/library/lnetatmo.py", line 250, in postRequest
    resp = urllib2.urlopen(req).read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request`

**Comment by baracudaz** [comment]
Thanks for reporting @sdecaux,

According to the errors there seem to be a problem with your credentials. Just make sure to put them in the `config.ini`  file _without_ quotes. 

```
[netatmo]
client_id     = 52b...23ca
client_secret = ghAV..rOAqEa
username      = your@email.com
password      = top-secret
```

**Comment by sdecaux** [comment]
oups, you're right!
thanks for the help...

BTW good idea to have placed these in a separate file...
